### ISSUE TITLE
[ptf11eon and PTF11eon] merge objects 

### ISSUE THREAD

**Issue by jparrent** [astrotransients/sne-external-spectra#12]
sne-external-spectra/UCB/PTF11eon-20130217.429-b.flm

This file and the other file for PTF11eon (SN 2011dh) are coming up as a separate entry for the catalog. That is, there is a ptf11eon group with UC SNDB + Arcavi+11 spectra, and a PTF11eon group with these two noisy spectra from UC SNDB. I'm pretty sure this is due to the ptf vs. PTF prefix for the files.

**Comment by guillochon** [comment]
This should be fixed now in https://github.com/astrotransients/sne-external-spectra/commit/a8d1f32fd065f4741d9387773936a9e89ff4a155, the UCB webpage from which the metadata was being pulled had not maintained consistent case for ptf11eon, I fixed it. Closing.
