### ISSUE TITLE
Still an issue with first 1993J spectrum

### ISSUE THREAD

**Issue by guillochon** [astrotransients/sne-external-spectra#3]
@jparrent It appears the [file](https://github.com/astrotransients/sne-external-spectra/blob/master/CfA_SNIbc/sn1993J/sn1993J-19941128.flm) still has at least two spectra in it, separated by non-ASCII characters. Also, comparing the data in the two spectra, they do appear to be different from one another. Are we sure the old spectra were all identical?

**Comment by jparrent** [comment]
In the old-old version, the original, the jargon of characters was the file names for the other files followed by that spectrum. Looks like the sn1993J-19950527.flm spectrum was not also removed from the sn1993J-19941128.flm file.

**Comment by guillochon** [comment]
Everything looks good now, closing this issue.
