### ISSUE TITLE
SNLS spectra plots

### ISSUE THREAD

**Issue by jparrent** [astrotransients/sne-external-spectra#5]
SNLS spectra are not showing up in the plots for some reason. Mousing-over reveals something is there.

**Comment by guillochon** [comment]
There's some issue where the spectra plots sometimes are invisible, but I haven't been able to track down the exact conditions that make that occur. It seems to happen randomly even when I just rerun the code without changes. I reran the script and the SNLS spectra are now visible, but I'm betting this will arise again.

**Comment by guillochon** [comment]
I believe I have fixed this, it was a result of using arrays of different sizes within the spectra plot, had a long discussion about it here: https://github.com/bokeh/bokeh/issues/3674. Closing this unless it recurs again.
