### ISSUE TITLE
[2003hv] reference update

### ISSUE THREAD

**Issue by jparrent** [astrotransients/sne-external-spectra#7]
sne-external-spectra/Suspect/Ia_spec_ascii_20110715/2003hv/

Just noticed this. All spectra in this folder (except for the last one; 2004-09-01) should be referenced to Leloudas et al. 2009. 
http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?db_key=ALL&warnings=YES&version=1&bibcode=2009A%26A...505..265L&nr_to_return=10&start_nr=1

The reference for the last spectrum (2003hv_20040901_51567_151964_00.dat
) goes to Gerardy et al. 2007. 
http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?db_key=ALL&warnings=YES&version=1&bibcode=2007ApJ...661..995G&nr_to_return=10&start_nr=1

What's odd is that these spectra come from the bulk download from SuSpect, yet they do not appear on SuSpect; sounds like they were in a stockpile and either forgotten, or received after SuSpect's retirement. 

FYI The Leloudas reference is there on the page for 03hv, but I guess what I'm getting after is that the mouse-over for these spectra points to SuSpect instead of Leloudas+09.

**Comment by guillochon** [comment]
I added a file [sources.json](https://github.com/astrotransients/sne-external-spectra/blob/master/Suspect/sources.json) to the Suspect sub-folder, this file is a dictionary of either the spectrum file name or an event name that link to ADS bibcodes. Individual filenames are given precedence over event names, but using an event name allows one to tag all spectra with a single reference (like the Leloudas reference above). The import script has been updated to read the sources file to add the proper sources to the final event files.

Also, I've added the 2003hv sources, so I'm closing this particular issue.
